### ISSUE TITLE
php-fpm version not available

### ISSUE THREAD

**Issue by farridav** [azavea/ansible-php-fpm#4]
Hi, the play is failing for me because of a missing php-fpm version in my sources..

```bash
failed: [vagrant] => {"failed": true}
stderr: E: Version '5.5.9+dfsg-1ubuntu4.4' for 'php5-fpm' was not found

stdout: Reading package lists...
Building dependency tree...
Reading state information...

msg: 'apt-get install 'php5-fpm=5.5.9+dfsg-1ubuntu4.4'' failed: E: Version '5.5.9+dfsg-1ubuntu4.4' for 'php5-fpm' was not found
```
I was thinking I could remove the default, and adjust the task to not include a version unless specified.. which will default php-fpm to whatever is the latest version in apt.. 

Ive added a PR for this if you could take a look, https://github.com/azavea/ansible-php-fpm/pull/5 cheers

**Comment by hectcastro** [comment]
We have been dealing with this issue across several projects by overriding variables like `php_fpm_version` at the `group_vars` level, or with wrapper roles. In addition, we occasionally make use globs (`*`) in the version specification:

```yaml
php_fpm_version: "5.5*"
```

If you set `php_fpm_version` to `*` it should install the more recent version.

**Comment by hectcastro** [comment]
Hey @farridav, were you able to get pass this issue with any of the suggestions above?

**Comment by farridav** [comment]
Hi, thanks for your response, I think in the end i tried another role, would the PR i put up not work for this? https://github.com/azavea/ansible-php-fpm/pull/5? plus by not setting a version it will take the latest available in the repositories anyway, people dont always want a specific version (like myself) :) thoughts?

**Comment by hectcastro** [comment]
I think that #5 *could* work, however, we've chosen to get around the issue with globs to avoid adding a "was a version number defined?" guard to all of the Ansible roles we maintain. In addition, we try to specify at least a major or minor version for packages that we depend on (other than some core system packages).

Apologies for not accepting your PR. Otherwise, I'm glad that you found an alternative role that works for your requirements.
